input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] == "sherlock-app" {
    mutate {
      replace => { "[log][category]" => "application" }
    }
    json {
      source => "message"
      target => "app"
      skip_on_invalid_json => true
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "sherlock-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
}
