- name: Configure machines
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - git
          - unzip
        state: present
